# Generated by Django 3.2.3 on 2021-06-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ejemplo1App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='image',
            field=models.ImageField(default='null', upload_to=''),
        ),
    ]
