# Generated by Django 3.2.3 on 2021-06-05 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ejemplo1App', '0003_citarapida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citarapida',
            name='hora',
            field=models.TimeField(),
        ),
    ]
