# Generated by Django 3.2.4 on 2021-06-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ejemplo1App', '0004_alter_citarapida_hora'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'Articulo', 'verbose_name_plural': 'Articulos'},
        ),
        migrations.AlterField(
            model_name='producto',
            name='image',
            field=models.ImageField(default='null', upload_to='producto'),
        ),
    ]
